name: "release-homebrew"
on:
  release:
    types: [released]

jobs:
  release:
    runs-on: macos-latest
    environment: release
    env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
    steps:
    - name: Open PR against homebrew/homebrew-cask
      run: |
        # Get latest version
        version=$(curl --silent "https://api.github.com/repos/git-ecosystem/git-credential-manager/releases/latest" |
          grep '"tag_name":' |
          sed -E 's/.*"v([0-9\.]+).*/\1/')

        # Ensure local Homebrew repository is up to date
        cd "$(brew --repository homebrew/cask)"
        git pull

        # Open PR to update to latest version
        brew bump-cask-pr git-credential-manager --version $version --no-audit --no-browse
